name: 01-decrement-app-react-ts

on:
  pull_request:
    branches:
      - main
    paths:
      - examples/01-decrement-app-react-ts

jobs:
  check:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: examples/01-decrement-app-react-ts
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn
      - run: yarn test
      - run: yarn build
